<?php

/**
 * @file
 * Contains menu_link_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function menu_link_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the menu_link_field module.
    case 'help.page.menu_link_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a field type allowing selection of a menu and a menu item within the selected menu.') . '</p>';
      return $output;

    default:
  }
}
